(() => {
'use strict';

const canvas=document.getElementById('scene'), ctx=canvas.getContext('2d',{alpha:false});
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const TAU=Math.PI*2, clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
let W=innerWidth,H=innerHeight,DPR=Math.min(devicePixelRatio||1,1.6);
let nextId=1, selected=null, dragging=false, orbiting=false, pointer={x:0,y:0}, last={x:0,y:0};
let tool='select', paused=false, timeScale=1, gravity=9.8, gravitySign=-1, lastTs=performance.now();
let yaw=.65,pitch=.42,camDist=20, flash=0, fps=0, fpsTimer=0, fpsFrames=0;
const objects=[]; const history=[]; const future=[]; const particles=[]; const shockwaves=[]; const portals=[];
const stats={booms:0,cuts:0,magnet:0,rain:0,flips:0,frozen:0,spawned:0};
const SAVE='n-sandbox-v03';
const COLORS=['#e9edf2','#e84d5b','#54a8ff','#f1c453','#63d483','#c77dff','#f39a4a','#8bd3dd'];
const TYPES={
 cube:{name:'Cube',shape:'box',s:[1.2,1.2,1.2],mass:1,bounce:.34,color:'#e9edf2'}, sphere:{name:'Sphere',shape:'sphere',s:[.82,.82,.82],mass:1,bounce:.52,color:'#c9d0d7'}, cylinder:{name:'Cylinder',shape:'cylinder',s:[.7,1.7,.7],mass:1.4,bounce:.35,color:'#b8c0ca'}, plank:{name:'Plank',shape:'box',s:[2.8,.34,.6],mass:1.5,bounce:.24,color:'#aeb7c1'}, wheel:{name:'Wheel',shape:'wheel',s:[.85,.42,.85],mass:1.2,bounce:.45,color:'#9fa8b2'}, domino:{name:'Domino',shape:'box',s:[.42,2.15,.24],mass:.8,bounce:.24,color:'#e3e7eb'}, crate:{name:'Crate',shape:'box',s:[1.35,1.35,1.35],mass:2.1,bounce:.2,color:'#8d97a3'}, balloon:{name:'Balloon',shape:'sphere',s:[.72,.88,.72],mass:.35,bounce:.2,color:'#e48b98'}, barrel:{name:'Barrel',shape:'cylinder',s:[.82,1.55,.82],mass:1.9,bounce:.31,color:'#a5abb3'}, bomb:{name:'Pulse Orb',shape:'sphere',s:[.6,.6,.6],mass:.7,bounce:.35,color:'#d1d6db'}, spring:{name:'Spring',shape:'cylinder',s:[.5,1.2,.5],mass:1.1,bounce:.8,color:'#c7ccd2'}, torso:{name:'Dummy Torso',shape:'box',s:[.72,1.1,.42],mass:2,bounce:.12,color:'#e9edf2'}, limb:{name:'Dummy Limb',shape:'box',s:[.28,.9,.28],mass:.7,bounce:.16,color:'#e9edf2'}, head:{name:'Dummy Head',shape:'sphere',s:[.42,.42,.42],mass:.6,bounce:.2,color:'#f2cda8'}
};
const MISSIONS=[
 ['Stack it high','Get 10 objects above the launch line.',10,()=>objects.filter(o=>o.p.y>6).length],
 ['Domino wave','Spawn 12 dominoes and knock 8 of them over.',8,()=>objects.filter(o=>o.type==='domino'&&o.v.length()>2).length],
 ['Paint storm','Paint 8 objects using any colours.',8,()=>objects.filter(o=>o.paintHits>0).length],
 ['Ragdoll lab','Create 2 dummies and knock them into each other.',2,()=>new Set(objects.filter(o=>o.group).map(o=>o.group)).size],
 ['Three cuts','Cut 3 blocks, then trigger a shockwave.',3,()=>stats.cuts],
 ['Magnet madness','Use the magnet on 8 different moments.',8,()=>stats.magnet],
 ['Gravity flip','Flip gravity twice while 6 objects are airborne.',2,()=>stats.flips],
 ['Object rain','Survive the 40-object rain.',40,()=>stats.rain?Math.min(40,objects.length):0],
 ['Tiny construction','Have 20 objects in one scene.',20,()=>objects.length],
 ['Chaos party','Activate a full Chaos Party.',1,()=>state.party?1:0]
];
let missionIndex=0, state={party:false,portalMode:false,missionDone:false};

const V={add:(a,b)=>({x:a.x+b.x,y:a.y+b.y,z:a.z+b.z}),sub:(a,b)=>({x:a.x-b.x,y:a.y-b.y,z:a.z-b.z}),mul:(a,s)=>({x:a.x*s,y:a.y*s,z:a.z*s}),len:a=>Math.hypot(a.x,a.y,a.z),norm:a=>{const l=Math.hypot(a.x,a.y,a.z)||1;return{x:a.x/l,y:a.y/l,z:a.z/l}},dot:(a,b)=>a.x*b.x+a.y*b.y+a.z*b.z};
function v3(x=0,y=0,z=0){return{x,y,z}}
function rotY(p,a){const c=Math.cos(a),s=Math.sin(a);return{x:p.x*c-p.z*s,y:p.y,z:p.x*s+p.z*c}}
function project(p){let q=rotY(p,yaw);const cp=Math.cos(pitch),sp=Math.sin(pitch);const y=q.y*cp-q.z*sp;const z=q.y*sp+q.z*cp+camDist;const x=q.x;const f=Math.min(W,H)*.92;const sc=f/Math.max(1.5,z);return{x:W/2+x*sc,y:H*.56-y*sc,z,sc};}
function resize(){W=innerWidth;H=innerHeight;DPR=Math.min(devicePixelRatio||1,1.6);canvas.width=Math.round(W*DPR);canvas.height=Math.round(H*DPR);ctx.setTransform(DPR,0,0,DPR,0,0)}
addEventListener('resize',resize);resize();
function toast(m){const n=document.createElement('div');n.className='toast glass';n.textContent=m;$('#toasts').appendChild(n);setTimeout(()=>{n.classList.add('out');setTimeout(()=>n.remove(),200)},1900)}
function audio(type){try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const a=audio.ctx??=new A();if(a.state==='suspended')a.resume();const o=a.createOscillator(),g=a.createGain();o.type='sine';o.frequency.value=type==='boom'?75:type==='paint'?420:260;g.gain.value=.025;o.connect(g);g.connect(a.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+(type==='boom'?.16:.07));o.stop(a.currentTime+(type==='boom'?.18:.08))}catch{}}

function boot(p,s){$('#boot-progress').style.width=p+'%';$('#boot-state').textContent=s}
function startup(){boot(15,'No external modules');boot(42,'Starting canvas renderer');boot(68,'Starting local physics');seed();boot(90,'Building sandbox tools');bind();boot(100,'Ready — instant mode');setTimeout(()=>$('#boot').classList.add('hide'),260);requestAnimationFrame(loop)}

function makeObj(type,x=0,y=6,z=0,opts={}){const d=TYPES[type]||TYPES.cube;const o={id:nextId++,type,p:v3(x,y,z),v:v3(opts.v?.x||0,opts.v?.y||0,opts.v?.z||0),r:v3(opts.r?.x||0,opts.r?.y||0,opts.r?.z||0),s:[...(opts.s||d.s)],mass:opts.mass??d.mass,bounce:opts.bounce??d.bounce,color:opts.color||d.color,frozen:false,age:0,ttl:opts.ttl||0,paintHits:0,group:opts.group||null,parent:opts.parent||null,local:opts.local||null,offset:Math.random()*10};objects.push(o);stats.spawned++;return o}
function seed(){objects.length=0;selected=null;stats.booms=stats.cuts=stats.magnet=stats.rain=stats.flips=stats.frozen=stats.spawned=0;state.party=false;for(let i=0;i<6;i++)makeObj('cube',(i-2.5)*1.5,1.2,0);makeObj('plank',0,3.1,0,{s:[4.8,.35,.65]});updateMission();}
function get(o){return o&&objects.find(x=>x.id===o.id)||null}
function radius(o){return Math.max(o.s[0],o.s[1],o.s[2])*.62}
function groundHit(o){const h=o.s[1]/2;o.p.y=Math.max(h+.02,o.p.y);if(o.p.y<=h+.03&&o.v.y<0)o.v.y=-o.v.y*o.bounce;o.v.x*=.992;o.v.z*=.992}
function bounds(o){const lim=15-r(o);if(o.p.x<-lim){o.p.x=-lim;o.v.x=Math.abs(o.v.x)*.55}if(o.p.x>lim){o.p.x=lim;o.v.x=-Math.abs(o.v.x)*.55}if(o.p.z<-lim){o.p.z=-lim;o.v.z=Math.abs(o.v.z)*.55}if(o.p.z>lim){o.p.z=lim;o.v.z=-Math.abs(o.v.z)*.55}}
function r(o){return Math.min(13.5,Math.max(.3,Math.max(o.s[0],o.s[2])))}
function simpleCollisions(){for(let i=0;i<objects.length;i++){const a=objects[i];if(a.frozen)continue;for(let j=i+1;j<objects.length;j++){const b=objects[j];if(b.frozen)continue;if(a.group&&a.group===b.group)continue;const dx=b.p.x-a.p.x,dz=b.p.z-a.p.z,dy=b.p.y-a.p.y;const d=Math.hypot(dx,dy,dz);const min=radius(a)+radius(b);if(d>0&&d<min*.78){const n={x:dx/d,y:dy/d,z:dz/d};const rel=V.dot(V.sub(b.v,a.v),n);if(rel<0){const imp=-(1+Math.min(a.bounce,b.bounce))*.5*rel;const ia=1/a.mass,ib=1/b.mass;a.v.x-=n.x*imp*ia;a.v.y-=n.y*imp*ia;a.v.z-=n.z*imp*ia;b.v.x+=n.x*imp*ib;b.v.y+=n.y*imp*ib;b.v.z+=n.z*imp*ib}const push=(min-d)*.035;a.p.x-=n.x*push;b.p.x+=n.x*push;a.p.y-=n.y*push;b.p.y+=n.y*push;a.p.z-=n.z*push;b.p.z+=n.z*push}}}}
function update(dt){if(paused)return;const steps=Math.min(4,Math.max(1,Math.round(timeScale*2)));for(let s=0;s<steps;s++){const h=dt*timeScale/steps;for(const o of objects){if(o.frozen)continue;o.age+=h;if(o.ttl&&o.age>o.ttl)o._remove=true;o.v.y+=gravity*gravitySign*h*(o.type==='balloon'?-0.22:1);if(o.type==='spring'&&o.p.y<6)o.v.y+=18*h;if(state.party)o.v.x+=Math.sin(performance.now()/370+o.offset)*2.2*h; // tiny chaos force
if(o.parent){const p=get(o.parent);if(p&&o.local){const target=V.add(p.p,rotY(o.local,p.r.y));const diff=V.sub(target,o.p);o.v.x+=diff.x*5*h;o.v.y+=diff.y*5*h;o.v.z+=diff.z*5*h}}
o.p.x+=o.v.x*h;o.p.y+=o.v.y*h;o.p.z+=o.v.z*h;o.r.x+=o.v.x*h*.08;o.r.y+=o.v.y*h*.04;o.r.z+=o.v.z*h*.08;groundHit(o);bounds(o)}simpleCollisions();handlePortals()}
for(let i=objects.length-1;i>=0;i--)if(objects[i]._remove)objects.splice(i,1);for(const p of particles){p.life-=dt*2;p.x+=p.vx*dt;p.y+=p.vy*dt;p.z+=p.vz*dt;p.vy-=6*dt}for(let i=particles.length-1;i>=0;i--)if(particles[i].life<=0)particles.splice(i,1);for(const s of shockwaves){s.life-=dt*1.45}for(let i=shockwaves.length-1;i>=0;i--)if(shockwaves[i].life<=0)shockwaves.splice(i,1);flash=Math.max(0,flash-dt*2.5)}
function handlePortals(){if(portals.length<2)return;for(const o of objects){for(let i=0;i<portals.length;i++){const p=portals[i];if(Math.hypot(o.p.x-p.x,o.p.z-p.z)<.7&&o.age>1.2){const q=portals[i?0:1];o.p.x=q.x+(o.p.x-p.x);o.p.z=q.z+(o.p.z-p.z);o.age=0;burst(q.x,q.y,q.z,'#8d7bff',10)}}}}
function burst(x,y,z,color='#e6eaee',count=18){for(let i=0;i<count;i++){const a=Math.random()*TAU,u=Math.random()*.9+.3;particles.push({x,y,z,vx:Math.cos(a)*u,vy:Math.random()*2.4,vz:Math.sin(a)*u,life:.8+Math.random()*.8,color})}}
function shockwave(x,y,z,force=11){stats.booms++;shockwaves.push({x,y,z,life:1,r:0});for(const o of objects){const q=V.sub(o.p,{x,y,z}),d=Math.max(.35,V.len(q));const n=V.norm(q);const k=Math.max(0,1-d/8)*force/o.mass;o.v.x+=n.x*k;o.v.y+=n.y*k+.5;o.v.z+=n.z*k}burst(x,y,z,'#f0f3f6',32);flash=1;audio('boom');toast('Shockwave released')}
function explodeSelected(){const o=get(selected);if(o)shockwave(o.p.x,o.p.y,o.p.z,13);else shockwave(0,2,0,9)}
function pushSelected(str=7){const o=get(selected);if(!o)return;const dir=V.norm({x:(Math.random()-.5),y:.45,z:(Math.random()-.5)});o.v=V.add(o.v,V.mul(dir,str/o.mass));burst(o.p.x,o.p.y,o.p.z,'#dce1e7',10);audio('push')}
function magnet(){const origin=get(selected)?.p||{x:0,y:2,z:0};stats.magnet++;for(const o of objects){const d=V.sub(origin,o.p),len=Math.max(.5,V.len(d));const k=Math.max(0,1-len/10)*6/o.mass;o.v.x+=d.x/len*k;o.v.y+=d.y/len*k;o.v.z+=d.z/len*k}toast('Magnet pulse')}
function gust(){for(const o of objects)o.v.x+=(1+Math.random()*2.5)/Math.sqrt(o.mass);burst(0,3,0,'#b9c4cf',24);toast('Gust')}
function freeze(){const o=get(selected);if(!o)return;o.frozen=!o.frozen;if(o.frozen)stats.frozen++;toast(o.frozen?'Frozen':'Released')}
function paint(color){const o=get(selected);if(!o)return;o.color=color;o.paintHits++;burst(o.p.x,o.p.y,o.p.z,color,8);audio('paint');updateMission()}
function cutSelected(){const o=get(selected);if(!o||!['cube','crate','plank','domino'].includes(o.type))return;record();const parts=[];const count=o.type==='plank'?3:2;const each=o.s[0]/count;for(let i=0;i<count;i++){const n=makeObj(o.type,o.p.x+(i-(count-1)/2)*each*1.15,o.p.y,o.p.z,{s:[each,o.s[1],o.s[2]],color:o.color,v:{x:o.v.x+(i-(count-1)/2)*.9,y:o.v.y+.8,z:o.v.z},bounce:o.bounce});parts.push(n)}objects.splice(objects.indexOf(o),1);selected=parts[0];stats.cuts++;burst(o.p.x,o.p.y,o.p.z,'#ecf0f4',14);audio('cut');toast('Object cut into pieces')}
function duplicate(){const o=get(selected);if(!o)return;record();selected=makeObj(o.type,o.p.x+.9,o.p.y+1.1,o.p.z+.4,{s:o.s,color:o.color,v:{x:o.v.x+1,y:o.v.y+1,z:o.v.z},group:null});toast('Duplicated')}
function removeSelected(){const o=get(selected);if(!o)return;record();objects.splice(objects.indexOf(o),1);selected=null;toast('Deleted')}
function toggleGravity(){gravitySign*=-1;stats.flips++;toast(gravitySign<0?'Gravity down':'Gravity UP');burst(0,2,0,'#cdd3da',16)}
function dropRain(){record();stats.rain++;for(let i=0;i<40;i++){const ks=Object.keys(TYPES).filter(k=>!['torso','limb','head'].includes(k));makeObj(ks[Math.floor(Math.random()*ks.length)],(Math.random()-.5)*13,9+Math.random()*8,(Math.random()-.5)*12,{color:COLORS[Math.floor(Math.random()*COLORS.length)]})}toast('40-object rain')}
function tower(){record();for(let i=0;i<12;i++)makeObj(i%2?'domino':'crate',0,1.1+i*1.25,0,{v:{x:0,y:0,z:0}});toast('Tower assembled')}
function party(){record();state.party=true;for(let i=0;i<18;i++)makeObj(i%3?'sphere':'plank',(Math.random()-.5)*8,4+Math.random()*5,(Math.random()-.5)*8);toggleGravity();gust();setTimeout(()=>state.party=false,12000);toast('Chaos Party: 12 seconds')}
function dummy(){const group='dummy_'+Date.now()+'_'+Math.random();const root=makeObj('torso',Math.random()*6-3,6+Math.random()*2,Math.random()*6-3,{group});const parts=[
 ['head',0,1.65,0],['limb',-.65,.55,0],['limb',.65,.55,0],['limb',-.35,-1.15,0],['limb',.35,-1.15,0]];
 for(const [type,x,y,z] of parts)makeObj(type,root.p.x+x,root.p.y+y,root.p.z+z,{group,parent:root.id,local:{x,y,z},color:type==='head'?'#f2cda8':'#d8dde2'});selected=root;toast('Dummy ragdoll spawned')}
function spawn(type){record();const x=(Math.random()-.5)*4,z=(Math.random()-.5)*4; if(type==='dummy'){dummy();return;}selected=makeObj(type,x,8,z,{color:COLORS[Math.floor(Math.random()*COLORS.length)]});const spawnedId=selected.id;if(type==='bomb')setTimeout(()=>{const o=objects.find(v=>v.id===spawnedId);if(o){shockwave(o.p.x,o.p.y,o.p.z,12);const i=objects.indexOf(o);if(i>=0)objects.splice(i,1);if(selected?.id===spawnedId)selected=null}},1400);toast(TYPES[type]?.name+' spawned')}
function moveSelected(dx,dy,dz){const o=get(selected);if(!o)return;o.p.x+=dx;o.p.y+=dy;o.p.z+=dz;o.v.x=dx*4;o.v.y=dy*4;o.v.z=dz*4}

function worldFromPointer(){const nx=(pointer.x/W-.5)*2,ny=(pointer.y/H-.56)*-2;const scale=camDist/Math.min(W,H);let q={x:nx*scale*5,y:Math.max(0,ny*scale*4),z:0};return rotY(q,-yaw)}
function pick(){let best=null,bd=Infinity;for(const o of objects){const s=project(o.p),rr=Math.max(10,Math.min(60,o.s[0]*s.sc*.9));const d=Math.hypot(pointer.x-s.x,pointer.y-s.y);if(d<rr&&d<bd){best=o;bd=d}}return best}

function drawBackground(){ctx.fillStyle='#080a0e';ctx.fillRect(0,0,W,H);const g=ctx.createRadialGradient(W*.5,H*.43,20,W*.5,H*.43,Math.max(W,H)*.72);g.addColorStop(0,'#171b22');g.addColorStop(1,'#080a0e');ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}
function faceColor(c,amt){const n=parseInt(c.slice(1),16),r=clamp(((n>>16)&255)*amt,0,255)|0,g=clamp(((n>>8)&255)*amt,0,255)|0,b=clamp((n&255)*amt,0,255)|0;return`rgb(${r},${g},${b})`}
function drawFloor(){const lines=[];for(let i=-15;i<=15;i+=1.5){lines.push([[i,0,-15],[i,0,15]]);lines.push([[-15,0,i],[15,0,i]])}ctx.lineWidth=1;for(const l of lines){const a=project(v3(...l[0])),b=project(v3(...l[1]));if(a.z<1||b.z<1)continue;ctx.strokeStyle='rgba(160,170,182,.10)';ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}const A=project(v3(-16,0,-16)),B=project(v3(16,0,-16)),C=project(v3(16,0,16)),D=project(v3(-16,0,16));ctx.fillStyle='#12161c';ctx.beginPath();ctx.moveTo(A.x,A.y);ctx.lineTo(B.x,B.y);ctx.lineTo(C.x,C.y);ctx.lineTo(D.x,D.y);ctx.closePath();ctx.fill()}
function drawBox(o){const [sx,sy,sz]=o.s.map(x=>x/2), pts=[v3(-sx,-sy,-sz),v3(sx,-sy,-sz),v3(sx,sy,-sz),v3(-sx,sy,-sz),v3(-sx,-sy,sz),v3(sx,-sy,sz),v3(sx,sy,sz),v3(-sx,sy,sz)];const p=pts.map(x=>{let y=rotY(x,o.r.y);y={x:y.x,y:y.y*Math.cos(o.r.x)-y.z*Math.sin(o.r.x),z:y.y*Math.sin(o.r.x)+y.z*Math.cos(o.r.x)};return project(V.add(o.p,y))});const fs=[[0,1,2,3,.8],[4,7,6,5,1.05],[0,4,5,1,.72],[3,2,6,7,.95],[1,5,6,2,.88],[0,3,7,4,.62]];fs.sort((a,b)=>{const za=a.slice(0,4).reduce((s,i)=>s+p[i].z,0);const zb=b.slice(0,4).reduce((s,i)=>s+p[i].z,0);return zb-za});for(const f of fs){ctx.fillStyle=faceColor(o.color,f[4]);ctx.beginPath();for(let i=0;i<4;i++){const q=p[f[i]];i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y)}ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(0,0,0,.24)';ctx.stroke()}}
function drawSphere(o){const p=project(o.p),rr=o.s[0]*p.sc;const g=ctx.createRadialGradient(p.x-rr*.35,p.y-rr*.4,rr*.12,p.x,p.y,rr);g.addColorStop(0,faceColor(o.color,1.32));g.addColorStop(.62,faceColor(o.color,1));g.addColorStop(1,faceColor(o.color,.62));ctx.fillStyle=g;ctx.beginPath();ctx.arc(p.x,p.y,rr,0,TAU);ctx.fill()}
function drawCylinder(o){const p=project(o.p),rx=o.s[0]*p.sc,ry=o.s[1]*p.sc*.48;ctx.fillStyle=faceColor(o.color,.85);ctx.beginPath();ctx.ellipse(p.x,p.y,rx,ry*.42,0,0,TAU);ctx.fill();ctx.fillStyle=faceColor(o.color,1.0);ctx.fillRect(p.x-rx,p.y-ry*.04,rx*2,ry*.65);ctx.fillStyle=faceColor(o.color,.74);ctx.beginPath();ctx.ellipse(p.x,p.y+ry*.61,rx,ry*.38,0,0,TAU);ctx.fill()}
function drawObject(o){if(o.type==='sphere'||o.type==='bomb'||o.type==='balloon'||o.type==='head')drawSphere(o);else if(o.type==='cylinder'||o.type==='wheel'||o.type==='barrel'||o.type==='spring')drawCylinder(o);else drawBox(o);if(o.frozen){const p=project(o.p);ctx.strokeStyle='rgba(140,205,255,.6)';ctx.beginPath();ctx.arc(p.x,p.y,Math.max(8,o.s[0]*p.sc*1.08),0,TAU);ctx.stroke()}}
function drawDummyHint(o){/* joints are spring-followers, no extra mesh needed */}
function render(){drawBackground();drawFloor();const sorted=[...objects].sort((a,b)=>project(b.p).z-project(a.p).z);for(const o of sorted){drawObject(o);if(o.group)drawDummyHint(o)}for(const s of shockwaves){const p=project(v3(s.x,s.y,s.z));ctx.strokeStyle=`rgba(240,244,248,${Math.max(0,s.life)*.55})`;ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,Math.max(0,(1-s.life)*130),0,TAU);ctx.stroke()}for(const p of particles){const q=project(v3(p.x,p.y,p.z));ctx.fillStyle=p.color;ctx.globalAlpha=Math.max(0,p.life);ctx.fillRect(q.x-2,q.y-2,4,4);ctx.globalAlpha=1}if(selected&&get(selected)){const o=get(selected),p=project(o.p),rr=Math.max(16,o.s[0]*p.sc*1.25);ctx.strokeStyle='rgba(255,255,255,.72)';ctx.lineWidth=2;ctx.setLineDash([5,4]);ctx.beginPath();ctx.arc(p.x,p.y,rr,0,TAU);ctx.stroke();ctx.setLineDash([])}if(portals.length){for(const p of portals){const q=project(v3(p.x,0.05,p.z));ctx.strokeStyle='#9a83ff';ctx.lineWidth=4;ctx.beginPath();ctx.arc(q.x,q.y,18,0,TAU);ctx.stroke()}}if(flash>0){ctx.fillStyle=`rgba(255,255,255,${flash*.15})`;ctx.fillRect(0,0,W,H)}}
function updateInspector(){const o=get(selected);$('#selection-name').textContent=o?TYPES[o.type]?.name||o.type:'Nothing selected';$('#selection-meta').textContent=o?`${o.frozen?'FROZEN · ':''}${Math.round(o.p.x*10)/10}, ${Math.round(o.p.y*10)/10}, ${Math.round(o.p.z*10)/10} · mass ${o.mass}`:'Click anything in the scene.';if(o)$('#elastic-value').textContent=o.bounce.toFixed(2)}
function updateMission(){const m=MISSIONS[missionIndex],p=Math.min(m[2],Math.floor(m[3]()));$('#mission-title').textContent=m[0];$('#mission-desc').textContent=m[1];$('#mission-count').textContent=`${p} / ${m[2]}`;$('#mission-progress').style.width=(p/m[2]*100)+'%';if(p>=m[2]&&!state.missionDone){state.missionDone=true;toast('Mission complete ✓');audio('paint')}}
function nextMission(){missionIndex=(missionIndex+1)%MISSIONS.length;state.missionDone=false;updateMission();toast(`Mission ${missionIndex+1}/${MISSIONS.length}`)}

function snapshot(){return JSON.stringify({objects:objects.map(o=>({type:o.type,p:o.p,v:o.v,r:o.r,s:o.s,mass:o.mass,bounce:o.bounce,color:o.color,group:o.group,parent:o.parent,local:o.local,frozen:o.frozen})),yaw,pitch,camDist,gravity,gravitySign})}
function restore(s){const d=JSON.parse(s);objects.length=0;nextId=1;const ids=new Map();for(const x of d.objects){const o=makeObj(x.type,x.p.x,x.p.y,x.p.z,{v:x.v,r:x.r,s:x.s,mass:x.mass,bounce:x.bounce,color:x.color,group:x.group,local:x.local});o.frozen=x.frozen;ids.set(x.id,o.id);o._oldParent=x.parent||null}for(const o of objects){if(o._oldParent)o.parent=ids.get(o._oldParent)||null;delete o._oldParent}yaw=d.yaw;pitch=d.pitch;camDist=d.camDist;gravity=d.gravity;gravitySign=d.gravitySign;selected=null;updateMission()}
function record(){if(history.lock)return;history.push(snapshot());if(history.length>25)history.shift();future.length=0}
function undo(){if(!history.length)return;future.push(snapshot());history.lock=true;restore(history.pop());history.lock=false;toast('Undo')}
function redo(){if(!future.length)return;history.push(snapshot());history.lock=true;restore(future.pop());history.lock=false;toast('Redo')}
function save(){localStorage.setItem(SAVE,snapshot());toast('Saved locally — no account required')}
function load(){const s=localStorage.getItem(SAVE);if(!s){toast('No local save');return}record();restore(s);toast('Loaded')}
function photo(){const link=document.createElement('a');link.download='n-sandbox-screenshot.png';link.href=canvas.toDataURL('image/png');link.click();toast('Screenshot created')}

function applyToolOnHit(o){selected=o;if(tool==='explode')explodeSelected();else if(tool==='cut')cutSelected();else if(tool==='magnet')magnet();else if(tool==='wind')gust();else if(tool==='freeze')freeze();else if(tool==='paint')paint(COLORS[Math.floor(Math.random()*COLORS.length)]);else if(tool==='grab'){const q=worldFromPointer();o.v=V.add(o.v,V.mul(V.norm(V.sub(q,o.p)),10/o.mass));toast('Pull') }else if(tool==='move'){record();o.p=worldFromPointer();o.p.y=Math.max(o.s[1]/2+.1,o.p.y)} }
function bind(){
 $('#spawn-toggle').onclick=()=>$('#spawn-menu').classList.toggle('open');document.addEventListener('pointerdown',e=>{if(!e.target.closest('.spawn-anchor'))$('#spawn-menu').classList.remove('open')});
 $$('[data-spawn]').forEach(b=>b.onclick=()=>{spawn(b.dataset.spawn);$('#spawn-menu').classList.remove('open')});
 $$('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));
 $('#duplicate-btn').onclick=duplicate;$('#delete-btn').onclick=removeSelected;$('#reset-btn').onclick=()=>{record();seed();toast('Sandbox reset')};$('#rain-btn').onclick=dropRain;$('#tower-btn').onclick=tower;$('#party-btn').onclick=party;
 $('#push-btn').onclick=()=>pushSelected(8);$('#cut-btn').onclick=cutSelected;$('#boom-btn').onclick=explodeSelected;$('#pause-btn').onclick=()=>{paused=!paused;$('#pause-btn').textContent=paused?'Resume':'Pause'};$('#slow-btn').onclick=()=>{timeScale=.25;toast('Time ×0.25')};$('#normal-btn').onclick=()=>{timeScale=1;toast('Time ×1')};$('#flip-btn').onclick=toggleGravity;$('#portal-btn').onclick=()=>{state.portalMode=true;toast('Click two points to place portals')};$('#save-btn').onclick=save;$('#load-btn').onclick=load;$('#undo-btn').onclick=undo;$('#redo-btn').onclick=redo;$('#photo-btn').onclick=photo;$('#mission-next').onclick=nextMission;
 $('#gravity').oninput=e=>{gravity=+e.target.value;$('#gravity-value').textContent=gravity.toFixed(1)};$('#elastic').oninput=e=>{const o=get(selected);if(o){o.bounce=+e.target.value;$('#elastic-value').textContent=o.bounce.toFixed(2)}};$$('.swatch').forEach(b=>b.onclick=()=>paint(b.dataset.color));
 canvas.addEventListener('pointerdown',e=>{pointer.x=e.clientX;pointer.y=e.clientY;last.x=e.clientX;last.y=e.clientY;if(e.button===1){orbiting=true;return}if(e.button!==0)return;if(state.portalMode){const q=worldFromPointer();portals.push({x:q.x,y:0,z:q.z});if(portals.length===2){state.portalMode=false;toast('Portal pair active');}return}const hit=pick();if(tool==='select'||tool==='move'){if(hit){record();applyToolOnHit(hit);dragging=true}else selected=null}else if(hit){record();applyToolOnHit(hit)}else if(tool==='wind')gust()});
 canvas.addEventListener('pointermove',e=>{pointer.x=e.clientX;pointer.y=e.clientY;if(orbiting){yaw-=(e.clientX-last.x)*.008;pitch=clamp(pitch-(e.clientY-last.y)*.006,.12,1.2);last.x=e.clientX;last.y=e.clientY;return}if(dragging&&selected&&tool==='select'){const o=get(selected);if(o){o.v.x+=(e.clientX-last.x)*.045;o.v.y-=(e.clientY-last.y)*.045;o.v.z+=(e.clientX-last.x)*.018}}last.x=e.clientX;last.y=e.clientY});
 canvas.addEventListener('pointerup',()=>{dragging=false;orbiting=false});canvas.addEventListener('wheel',e=>{camDist=clamp(camDist+e.deltaY*.012,8,34)},{passive:true});
 addEventListener('keydown',e=>{if(e.target&&['INPUT','TEXTAREA'].includes(e.target.tagName))return;const k=e.key.toLowerCase();if(k==='?'){ $('#help').classList.remove('hidden');return }if(k==='escape'){ $('#help').classList.add('hidden');return }if(e.key==='Delete')return removeSelected();if(k==='r')return $('#reset-btn').click();if(k==='v')return setTool('move');if(k==='c')return setTool('cut');if(k==='e')return setTool('explode');if(k==='m')return setTool('magnet');if(k==='g')return setTool('wind');if(k==='f')return setTool('freeze');if(k==='p')return setTool('paint');if(k==='h')return setTool('grab');if(k==='d')return duplicate();if(k===' '){e.preventDefault();$('#pause-btn').click();return}if(k==='1')return setTool('select');const map={2:'cube',3:'sphere',4:'cylinder',5:'plank',6:'wheel',7:'domino',8:'crate',9:'balloon',0:'barrel',q:'dummy',w:'bomb',t:'spring'};if(map[k])spawn(map[k])});$('#close-help').onclick=()=>$('#help').classList.add('hidden')}
function setTool(t){tool=t;$$('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));$('#hint').innerHTML=`<b>${t.toUpperCase()}</b> · click object to use · <b>MMB</b> orbit · <b>wheel</b> zoom · <b>?</b> controls`}
function loop(ts){const dt=Math.min(.035,(ts-lastTs)/1000);lastTs=ts;fpsFrames++;fpsTimer+=dt;if(fpsTimer>.5){fps=Math.round(fpsFrames/fpsTimer);fpsFrames=0;fpsTimer=0;$('#fps').textContent=fps+' FPS';}update(dt);render();updateInspector();updateMission();$('#object-count').textContent=objects.length+' objects';requestAnimationFrame(loop)}
startup();
})();
